// Psychological service, anti-bullying, cyber-safety, prevention, helplines (ORDER-114 §G item 57).
// Legal texts read on adilet.zan.kz (24.09.2026):
//  · Rules of the psychological-pedagogical support service (СППС / ППҚҚ) — Order of the Minister of Education
//    of 29.04.2025 No. 92 (reg. No. 36047; restated by order 29.05.2026 No. 144-НҚ) — V2500036047.
//    It replaced the 2022 rules (Order No. 377). Paras used: 4 (collegial body, composition), 5 (principles),
//    8 (five directions), 12 (written parental consent), 23 (crisis cases → psychological support centres).
//  · Rules on preventing bullying of a child — Order No. 506 of 21.12.2022 (reg. No. 31180) — V2200031180.
//    Re-read in full on 25.09.2026 (kz + ru). Paras used: 2 (definition incl. cyberbullying), 4 (annual plan; awareness
//    at least once a quarter), 7 (log), 8 (head within 1 day), 9 (deputy: talk within 1 working day, peaceful settlement,
//    report within 1 working day), 10 (local education authority: decision within 2 working days; rehabilitation /
//    adaptation decision agreed with parents; mediator with consent), 11 (parents may appeal — APPK Art. 91 p. 5),
//    12 (individual plan; initiator on the internal school register; no improvement within 6 months → КДН/КІК),
//    15 (school informs in writing at once: local education authority, the child's school, police), 17 (ethics council).
//  · Law "On Education", Art. 49 para 2 sub-para 1-1 (parents control phone/internet use) — Z070000319_.
//  · Law "On Prevention of Offences" of 30.12.2025 No. 245-VIII — Z2500000245 (read 25.09.2026). Art. 23 = competence
//    of educational organisations (sub-paras 1, 3, 4, 9, 10, 11, 13, 14 used). Art. 85 p. 3: it REPEALED the Law of
//    09.07.2004 No. 591 "On preventing offences among minors…" (so No. 591 is NOT cited as current).
//  · Helpline 111 — gov4c.kz/kz/about/kontakt-tsentr-111/ (24/7, free from all mobile operators, operated by the
//    Government for Citizens State Corporation since 16.10.2023). Helpline 150 — National helpline for children and
//    youth (Union of Crisis Centres, since 2005; anonymous) — forbes.kz, tengrinews.kz; hours vary → not stated.
const X = (kz, ru, en) => ({ kz, ru, en });

// Documents of the upbringing group (spps-order, spps-plan, bullying-plan, offence-plan, prevention-council,
// parents-plan) live in src/data/documents.mjs (group 'upbringing'). ubDoc() is kept for upbringing.mjs / parents.mjs.
export const ubDoc = (docById, id) => docById(id);

export default {
  slug: 'psychology',
  group: 'upbringing',
  order: 30,
  styles: ['upbringing'],
  title: X('Психологиялық қызмет', 'Психологическая служба', 'Psychological service'),
  description: X(
    'Психологиялық-педагогикалық қолдау, буллингтің алдын алу, киберқауіпсіздік, сенім телефондары 111 және 150, қиын жағдайда не істеу керек.',
    'Психолого-педагогическое сопровождение, профилактика буллинга, кибербезопасность, телефоны доверия 111 и 150, что делать в трудной ситуации.',
    'Psychological support, bullying prevention, cyber-safety, helplines 111 and 150, and what to do in a difficult situation.',
  ),
  lead: X(
    'Әр бала мектепте қауіпсіз әрі қорғалған болуы тиіс. Мұнда — көмек қайдан алуға болатыны, буллингке қалай ден қойылатыны және ата-аналарға кеңестер.',
    'Каждый ребёнок должен чувствовать себя в школе в безопасности. Здесь — куда обратиться за помощью, как школа реагирует на буллинг и советы родителям.',
    'Every child should feel safe at school. Here is where to get help, how bullying is handled and advice for parents.',
  ),
  published: '2026-09-24T10:00',
  updated: '2026-09-24T10:00',

  render(lang, { ui, S, L, href, docById }) {
    const adilet = (id) => `https://adilet.zan.kz/${lang === 'kz' ? 'kaz' : 'rus'}/docs/${id}`;
    const R92 = adilet('V2500036047');
    const R506 = adilet('V2200031180');
    const LAW = adilet('Z070000319_');
    const LAW245 = adilet('Z2500000245');
    const GOV111 = `https://gov4c.kz/${lang === 'kz' ? 'kz' : 'ru'}/about/kontakt-tsentr-111/`;

    // ---------------------------------------------------------------- helplines (top)
    const line = (c, num, tel, label, note, tag, ic) => `<li class="ub-line ${c}"><a href="tel:${tel}"><span class="ub-line__num">${ui.icon(ic, { size: 30 })}<span class="ub-line__digits">${String(num).replace(/^(.*\))\s*(.+)$/, '<span class="ub-nw">$1</span> <span class="ub-nw">$2</span>')}</span></span><span class="ub-line__label">${L(label)}</span><span class="ub-line__note">${L(note)}</span><span class="ub-line__tag">${L(tag)}</span></a></li>`;
    const lines = `<ul class="ub-lines" role="list">
${line('ub-c-coral', '111', '111', X('Отбасы, әйелдер мен балалардың құқықтарын қорғау мәселелері жөніндегі байланыс орталығы', 'Контакт-центр по вопросам семьи, защиты прав женщин и детей', 'Contact centre for family, women’s and children’s rights'), X('Психологиялық, құқықтық және ақпараттық көмек, бала құқығының бұзылуы туралы хабарлау.', 'Психологическая, правовая и информационная помощь, сообщение о нарушении прав ребёнка.', 'Psychological, legal and information support; report a violation of a child’s rights.'), X('Тәулік бойы · тегін', 'Круглосуточно · бесплатно', '24/7 · free'), 'phone')}
${line('ub-c-sun', '150', '150', X('Балалар мен жастарға арналған ұлттық сенім телефоны', 'Национальная телефонная линия доверия для детей и молодёжи', 'National helpline for children and young people'), X('Психологтармен анонимді әңгіме: атыңды айтпай-ақ көмек алуға болады.', 'Анонимный разговор с психологом: помощь можно получить, не называя имени.', 'An anonymous talk with a psychologist — no need to give your name.'), X('Анонимді', 'Анонимно', 'Anonymous'), 'chat')}
${line('ub-c-sky', '112', '112', X('Шұғыл қызметтер', 'Экстренные службы', 'Emergency services'), X('Өмірге немесе денсаулыққа қауіп төнсе — дереу қоңырау шалыңыз. Полиция — 102, жедел жәрдем — 103.', 'Если есть угроза жизни или здоровью — звоните немедленно. Полиция — 102, скорая помощь — 103.', 'If life or health is in danger, call at once. Police — 102, ambulance — 103.'), X('Шұғыл', 'Экстренно', 'Emergency'), 'warn')}
${line('ub-c-mint ub-line--sm', S.contacts.phone.display, S.contacts.phone.tel, X('Мектеп', 'Школа', 'The school'), X('Сынып жетекшісіне, директор орынбасарына немесе педагог-психологқа хабарласу үшін.', 'Чтобы связаться с классным руководителем, заместителем директора или педагогом-психологом.', 'To reach the class teacher, the deputy director or the school psychologist.'), X('Мектеп телефоны', 'Телефон школы', 'School phone'), 'school')}
</ul>
<p class="ub-lines-note">${L(X(
      `111 туралы: ${ui.extLink(GOV111, '«Азаматтарға арналған үкімет» МК, gov4c.kz')}. 150 желісінің жұмыс уақыты өзгеруі мүмкін — шұғыл жағдайда 112 немесе 111 нөміріне хабарласыңыз.`,
      `О линии 111: ${ui.extLink(GOV111, 'Госкорпорация «Правительство для граждан», gov4c.kz')}. Режим работы линии 150 может меняться — в экстренной ситуации звоните 112 или 111.`,
      `About 111: ${ui.extLink(GOV111, 'Government for Citizens State Corporation, gov4c.kz')}. Line 150’s hours may change — in an emergency call 112 or 111.`,
    ))}</p>`;

    // ---------------------------------------------------------------- service (СППС)
    const serviceText = ui.prose(L(X(
      `<p>${ui.extLink(R92, 'ҚР Оқу-ағарту министрінің 2025 жылғы 29 сәуірдегі № 92 бұйрығымен')} бекітілген қағидалар бойынша әр мектепте <strong>психологиялық-педагогикалық қолдау қызметі</strong> (ППҚҚ) болуы тиіс. Бұл — білім алушылардың психологиялық әл-ауқатын қамтамасыз етуге жауапты алқалы орган. Оның құрамын мектеп басшысы бұйрықпен бекітеді: директор орынбасарлары, педагог-психолог, әлеуметтік педагог және басқа мамандар. Сынып жетекшілері мен пән мұғалімдері де қолдау процесіне қатысады.</p><p>«Керемет» мектебіндегі қызметтің құрамы туралы бұйрық пен жұмыс жоспары осы беттің «Құжаттар» бөлімінде жарияланады.</p>`,
      `<p>По Правилам, утверждённым ${ui.extLink(R92, 'приказом Министра просвещения РК от 29 апреля 2025 года № 92')}, в каждой школе должна действовать <strong>служба психолого-педагогического сопровождения</strong> (СППС) — коллегиальный орган, отвечающий за психологическое благополучие обучающихся. Её состав руководитель школы утверждает приказом: заместители директора, педагог-психолог, социальный педагог и другие специалисты. В сопровождении участвуют также классные руководители и учителя-предметники.</p><p>Приказ о составе службы школы «Керемет» и её план работы будут опубликованы в разделе «Документы» на этой странице.</p>`,
      `<p>Under the Rules approved by ${ui.extLink(R92, 'Order No. 92 of the Minister of Education of 29 April 2025')}, every school must have a <strong>psychological and pedagogical support service</strong> — a collegial body responsible for pupils’ psychological well-being. The head approves its members by order: deputy directors, the school psychologist, the social pedagogue and other specialists. Class teachers and subject teachers take part in the support too.</p><p>Keremet’s order on the service’s membership and its work plan will be published in the “Documents” part of this page.</p>`,
    )));
    const directions = ui.cards([
      { icon: 'search', title: X('Диагностика', 'Диагностика', 'Assessment'), text: X('Оқудағы, дамудағы және тәрбиедегі қиындықтарды ерте анықтау.', 'Раннее выявление трудностей в обучении, развитии и воспитании.', 'Spotting difficulties in learning, development and behaviour early.') },
      { icon: 'chat', title: X('Кеңес беру', 'Консультирование', 'Counselling'), text: X('Оқушыларға, ата-аналарға және педагогтерге жеке және топтық кеңес.', 'Индивидуальные и групповые консультации для учеников, родителей и педагогов.', 'Individual and group counselling for pupils, parents and teachers.') },
      { icon: 'sparkles', title: X('Дамыту және түзету', 'Развитие и коррекция', 'Development'), text: X('Жеке, шағын топтық және топтық дамыту сабақтары.', 'Индивидуальные, подгрупповые и групповые развивающие занятия.', 'Individual, small-group and group developmental sessions.') },
      { icon: 'bulb', title: X('Психологиялық ағарту', 'Просвещение', 'Awareness'), text: X('Ата-аналар мен педагогтерге арналған семинарлар, тренингтер, ұсынымдар.', 'Семинары, тренинги и рекомендации для родителей и педагогов.', 'Seminars, trainings and guidance for parents and teachers.') },
      { icon: 'grid', title: X('Ұйымдастыру-әдістемелік жұмыс', 'Организационно-методическая работа', 'Planning and methods'), text: X('Білім беру ортасының жағдайын бақылау және нәтижелерді талдау.', 'Мониторинг условий образовательной среды и анализ результатов.', 'Monitoring the school environment and analysing results.') },
    ], { cols: 3 });
    const principles = ui.split({
      ratio: '1:1',
      left: ui.callout({ type: 'ok', icon: 'lock', title: X('Құпиялылық', 'Конфиденциальность', 'Confidentiality'), text: X('Мамандар баланың құқықтары мен мүдделерін сақтай отырып, алынған ақпараттың құпиялылығын сақтайды (Қағидалардың 5-тармағы).', 'Специалисты соблюдают конфиденциальность полученной информации с учётом прав и интересов ребёнка (п. 5 Правил).', 'Specialists keep information confidential, respecting the child’s rights and interests (Rules, para. 5).') }),
      right: ui.callout({ type: 'info', icon: 'doc', title: X('Ата-ананың жазбаша келісімі', 'Письменное согласие родителей', 'Written parental consent'), text: X('Баламен психологиялық диагностика, кеңес беру және тренингтер ата-ананың немесе заңды өкілдің жазбаша келісімімен ғана жүргізіледі (12-тармақ).', 'Психологическая диагностика, консультирование и тренинги с ребёнком проводятся только с письменного согласия родителей или законных представителей (п. 12).', 'Psychological assessment, counselling and trainings with a child take place only with the written consent of a parent or legal guardian (para. 12).') }),
    });
    const psychologist = ui.pending({
      title: X('Педагог-психолог: байланыс және қабылдау уақыты', 'Педагог-психолог: контакты и часы приёма', 'School psychologist: contacts and hours'),
      note: X(
        'Педагог-психологтың және әлеуметтік педагогтің аты-жөні, кабинеті, қабылдау күндері мен уақыты, сондай-ақ қызметтің 2026–2027 оқу жылына арналған жұмыс жоспары осы жерде жарияланады. Оған дейін кездесуге сынып жетекшісі немесе мектеп телефоны арқылы жазылуға болады.',
        'Здесь будут опубликованы ФИО педагога-психолога и социального педагога, кабинет, дни и часы приёма, а также план работы службы на 2026–2027 учебный год. А пока записаться на встречу можно через классного руководителя или по телефону школы.',
        'The names of the school psychologist and social pedagogue, their room and consultation hours, and the service’s 2026–2027 work plan will be published here. Until then, book a meeting through the class teacher or the school phone.',
      ),
    });

    // ---------------------------------------------------------------- bullying
    const definition = ui.quote({
      text: X(
        'Баланы жәбірлеу (буллинг) — қорлау сипатындағы жүйелі (екі және одан көп) әрекеттер, қудалау және (немесе) қорқыту, <…> сол сияқты жария түрде немесе масс-медиа және (немесе) телекоммуникация желілері және (немесе) онлайн-платформалар пайдаланыла отырып жасалған дәл сол әрекеттер (кибербуллинг).',
        'Травля (буллинг) ребёнка — систематические (два и более раза) действия унизительного характера, преследование и (или) запугивание, <…> а равно те же действия, совершённые публично или с использованием масс-медиа и (или) сетей телекоммуникаций, и (или) онлайн-платформ (кибербуллинг).',
        'Bullying of a child is systematic (two or more times) humiliating actions, harassment and/or intimidation, <…> including the same actions committed publicly or via mass media, telecommunications networks and/or online platforms (cyberbullying).',
      ),
      cite: X('Баланы жәбірлеудің (буллингтің) профилактикасы қағидалары, 2-тармақ', 'Правила профилактики травли (буллинга) ребёнка, п. 2', 'Rules on preventing bullying of a child, para. 2'),
      role: X('ҚР Оқу-ағарту министрінің 21.12.2022 ж. № 506 бұйрығы', 'Приказ Министра просвещения РК от 21.12.2022 № 506', 'Order No. 506 of the Minister of Education, 21.12.2022'),
    });
    const zero = ui.cards([
      { icon: 'calendar', title: X('Жыл сайынғы жоспар', 'Ежегодный план', 'Annual plan'), text: X('Директор әр оқу жылының басында буллингтің профилактикасы жоспарын бекітеді.', 'Директор к началу каждого учебного года утверждает план профилактики буллинга.', 'The head approves a bullying prevention plan at the start of each school year.') },
      { icon: 'users', title: X('Тоқсан сайын түсіндіру', 'Разъяснение каждую четверть', 'Awareness every term'), text: X('Оқушылармен, педагогтермен және ата-аналармен әңгімелер, сынып сағаттары, жиналыстар — тоқсанына кемінде бір рет.', 'Беседы, классные часы, родительские собрания для учеников, педагогов и родителей — не реже раза в четверть.', 'Talks, class hours and parent meetings for pupils, teachers and parents — at least once a term.') },
      { icon: 'shield', title: X('Нөлдік төзімділік', 'Нулевая терпимость', 'Zero tolerance'), text: X('Мектеп қатысушылардың құқықтарын құрметтейтін және буллингке жол бермейтін орта қалыптастырады.', 'Школа формирует среду уважения к правам участников и нулевой терпимости к травле.', 'The school builds a culture of respect and zero tolerance to bullying.') },
    ], { cols: 3 });
    // Two tracks, exactly as Rules No. 506 set them out: (A) what the school does itself (paras 7–9, 15),
    // (B) the decision of the local education authority and what follows (paras 10–12).
    const stepA = (time, title, text, tag) => ({ time, title, text, tag });
    const procedureSchool = ui.timeline([
      stepA(X('Бірден', 'Сразу', 'At once'), X('Хабар журналға тіркеледі', 'Сообщение регистрируется в журнале', 'The report is logged'), X('Жауапты тұлға түскен хабарды баланы жәбірлеу (буллинг) туралы ақпаратты есепке алу журналына тіркейді.', 'Ответственное лицо регистрирует информацию в журнале учёта информации о травле (буллинге) ребёнка.', 'The responsible person records it in the log of reports of bullying.'), X('7-тармақ', 'п. 7', 'para 7')),
      stepA(X('Дереу, жазбаша', 'Незамедлительно, письменно', 'Immediately, in writing'), X('Білім басқармасы мен полиция хабардар етіледі', 'Информируются управление образования и полиция', 'The education department and the police are notified'), X('Мектеп буллинг фактісі туралы <strong>дереу жазбаша түрде</strong> хабарлайды: білім беру саласындағы жергілікті атқарушы органға (қалалық білім басқармасы), баланың оқу орны бойынша білім беру ұйымына және ішкі істер органдарына (полицияға).', 'Школа <strong>незамедлительно в письменном виде</strong> информирует о факте травли: местный исполнительный орган в сфере образования (городское управление образования), организацию образования по месту учёбы ребёнка и органы внутренних дел (полицию).', 'The school notifies <strong>immediately and in writing</strong>: the local education authority (the city education department), the school where the child studies, and the police.'), X('15-тармақ', 'п. 15', 'para 15')),
      stepA(X('1 күн ішінде', 'В течение 1 дня', 'Within 1 day'), X('Директор хабардар болады', 'Информация доводится до директора', 'The head is informed'), X('Түскен ақпарат мектеп басшысына жеткізіледі.', 'Поступившая информация доводится до руководителя школы.', 'The information reaches the head of the school.'), X('8-тармақ', 'п. 8', 'para 8')),
      stepA(X('1 жұмыс күні ішінде', 'В течение 1 рабочего дня', 'Within 1 working day'), X('Әңгіме', 'Беседа', 'Conversations'), X('Тәрбие жұмысы жөніндегі директор орынбасары сынып жетекшісі мен педагог-психологты тарта отырып, жәбірленген баламен, бастамашымен және олардың заңды өкілдерімен сөйлеседі; қатысушылар туралы бастапқы ақпаратты жинайды.', 'Заместитель директора по воспитательной работе с классным руководителем и педагогом-психологом беседует с пострадавшим ребёнком, инициатором и их законными представителями; собирает первичную информацию об участниках.', 'The deputy director for upbringing, with the class teacher and psychologist, talks to the child, the initiator and their parents, and gathers the first facts about those involved.'), X('9-тармақ', 'п. 9', 'para 9')),
      stepA(X('Келесі 1 жұмыс күні ішінде', 'В течение следующего рабочего дня', 'Within the next working day'), X('Бейбіт реттеу және директорға есеп', 'Мирное урегулирование и доклад директору', 'Peaceful settlement and report to the head'), X('Жанжалды бейбіт жолмен шешу шаралары қабылданады; медициналық көрсетілім болса, медициналық көмекке жәрдемдеседі. Әңгімеден кейін 1 жұмыс күні ішінде нәтижесі директорға жеткізіледі.', 'Принимаются меры по мирному урегулированию конфликта; при медицинских показаниях — содействие в оказании медицинской помощи. В течение 1 рабочего дня после беседы результаты передаются директору.', 'Steps are taken to settle the conflict peacefully, with help to get medical care if needed. Within 1 working day of the conversations the results go to the head.'), X('9-тармақ', 'п. 9', 'para 9')),
    ], { cls: 'ub-proc' });
    const procedureAuthority = ui.timeline([
      stepA(X('2 жұмыс күні ішінде', 'В течение 2 рабочих дней', 'Within 2 working days'), X('Білім басқармасы шешім қабылдайды', 'Управление образования принимает решение', 'The education department decides'), X('Жиналған деректер негізінде буллингті тану немесе танымау туралы шешім шығарады. Танылса — ата-аналармен келісе отырып, жәбірленген баланы әлеуметтік оңалту және бастамашыны әлеуметтік бейімдеу туралы шешім қабылдайды; тараптардың келісімімен медиатор тартылуы мүмкін.', 'На основе собранных данных принимает решение о признании или непризнании травли. Если травля признана — по согласованию с родителями решает о социальной реабилитации пострадавшего и социальной адаптации инициатора; с согласия сторон может привлекаться медиатор.', 'Based on the facts gathered, it decides whether this is bullying. If so, it decides — in agreement with the parents — on rehabilitation for the child and social adaptation for the initiator; a mediator may be involved with the parties’ consent.'), X('10-тармақ', 'п. 10', 'para 10')),
      stepA(X('Келіспесеңіз', 'При несогласии', 'If you disagree'), X('Ата-аналар шешімге шағым жасай алады', 'Родители могут обжаловать решение', 'Parents may appeal the decision'), X('Жәбірленген баланың да, бастамашының да заңды өкілдері білім басқармасының шешімімен келіспесе, оған Әкімшілік рәсімдік-процестік кодекстің 91-бабының 5-тармағына сәйкес шағым жасайды.', 'Законные представители как пострадавшего ребёнка, так и инициатора при несогласии с решением управления образования обжалуют его в соответствии с п. 5 ст. 91 Административного процедурно-процессуального кодекса РК.', 'The parents of either the child or the initiator can appeal the education department’s decision under Art. 91(5) of the Administrative Procedure Code.'), X('11-тармақ', 'п. 11', 'para 11')),
      stepA(X('Шешім алынғаннан кейін', 'После получения решения', 'Once the decision arrives'), X('Екі тарапқа жеке жоспар', 'Индивидуальный план для обеих сторон', 'An individual plan for both sides'), X('Мектеп буллингке қатысушыларға психологиялық қолдаудың жеке жұмыс жоспарын әзірлейді: жәбірленген баланы әлеуметтік оңалту және бастамашыны әлеуметтік бейімдеу шаралары.', 'Школа разрабатывает индивидуальный план психологической поддержки участников: меры социальной реабилитации пострадавшего и социальной адаптации инициатора.', 'The school draws up an individual support plan: rehabilitation measures for the child who was bullied and social adaptation for the initiator.'), X('12-тармақ', 'п. 12', 'para 12')),
      stepA(X('6 ай бақылау', '6 месяцев наблюдения', '6 months of follow-up'), X('Бастамашы мектепішілік есепке қойылады', 'Инициатор ставится на внутришкольный учёт', 'The initiator is placed on the school’s internal register'), X('Мектеп бастамашыны мектепішілік есепке қойып, мінез-құлқының түзелуін бақылайды. Есепке қойылған күннен бастап 6 ай ішінде оң өзгеріс болмаса, материалдар Кәмелетке толмағандардың істері және олардың құқықтарын қорғау жөніндегі комиссияға (КІК) жіберіледі.', 'Школа ставит инициатора на внутришкольный учёт и ведёт мониторинг изменений в его поведении. Если в течение 6 месяцев со дня постановки на учёт положительных изменений нет, материалы направляются в комиссию по делам несовершеннолетних и защите их прав (КДН).', 'The school puts the initiator on its internal register and monitors their behaviour. If it does not improve within 6 months of that date, the case goes to the Commission on Juvenile Affairs and the Protection of their Rights (KDN).'), X('12-тармақ', 'п. 12', 'para 12')),
    ], { cls: 'ub-proc' });
    const procedure = `<div class="ub-proc-grid">
<div class="ub-proc-col"><p class="ub-proc-col__k">${ui.icon('school', { size: 18 })}${L(X('А. Мектеп', 'А. Школа', 'A. The school'))}</p>${procedureSchool}</div>
<div class="ub-proc-col"><p class="ub-proc-col__k">${ui.icon('building', { size: 18 })}${L(X('Б. Білім басқармасы және одан әрі', 'Б. Управление образования и далее', 'B. The education department and after'))}</p>${procedureAuthority}</div>
</div>
<p class="ub-src"><strong>${L(X('Дереккөз:', 'Источник:', 'Source:'))}</strong>${ui.extLink(R506, X('Баланы жәбірлеудің (буллингтің) профилактикасы қағидалары, 7–12, 15-тармақтар', 'Правила профилактики травли (буллинга) ребёнка, пп. 7–12, 15', 'Rules on preventing bullying of a child, paras 7–12 and 15'))}</p>`;
    const teacherNote = ui.callout({ type: 'warn', title: X('Егер баланы педагог қорласа', 'Если ребёнка унижает педагог', 'If a teacher bullies a child'), text: X('Мұндай жағдай педагогикалық әдеп жөніндегі кеңесте қаралады (Қағидалардың 17-тармағы). Өтінішті директорға немесе сайттағы кері байланыс формасы арқылы жіберуге болады.', 'Такой случай рассматривается советом по педагогической этике (п. 17 Правил). Обращение можно направить директору или через форму обратной связи на сайте.', 'Such cases are reviewed by the pedagogical ethics council (Rules, para. 17). You can write to the director or use the feedback form on this site.') });

    // ---------------------------------------------------------------- cyber-safety
    const cyber = ui.cards([
      { icon: 'lock', title: X('Жеке деректерді қорғау', 'Берегите личные данные', 'Protect personal data'), text: X('Құпиясөзді, мекенжайды, телефон нөмірін және геолокацияны бөтен адамдармен бөліспеңіз.', 'Не сообщайте посторонним пароли, адрес, номер телефона и геолокацию.', 'Never share passwords, your address, phone number or location with strangers.') },
      { icon: 'image', title: X('Скриншот жасаңыз', 'Сохраните доказательства', 'Keep evidence'), text: X('Қорлау мен қорқыту хабарламаларына жауап бермей, скриншот жасап, ересекке көрсетіңіз.', 'Не отвечайте на оскорбления и угрозы — сделайте скриншот и покажите взрослому.', 'Do not reply to insults or threats — take a screenshot and show an adult.') },
      { icon: 'close', title: X('Бұғаттаңыз және шағымданыңыз', 'Заблокируйте и пожалуйтесь', 'Block and report'), text: X('Әлеуметтік желі мен мессенджердегі «бұғаттау» және «шағымдану» функцияларын пайдаланыңыз.', 'Используйте функции «заблокировать» и «пожаловаться» в соцсетях и мессенджерах.', 'Use the “block” and “report” tools in social networks and messengers.') },
      { icon: 'users', title: X('Онлайн танысқа кездеспеңіз', 'Не встречайтесь с онлайн-знакомыми', 'Don’t meet online strangers'), text: X('Интернеттегі таныспен ата-анасыз кездесуге бармаңыз.', 'Не ходите на встречу с интернет-знакомым без родителей.', 'Never meet someone you only know online without your parents.') },
      { icon: 'clock', title: X('Экран уақыты', 'Экранное время', 'Screen time'), text: X('Отбасылық ереже келісіңіз: ұйқы алдында және сабақ кезінде гаджетсіз.', 'Договоритесь о семейных правилах: без гаджетов перед сном и во время уроков.', 'Agree family rules: no gadgets at bedtime or during lessons.') },
      { icon: 'shield', title: X('Ата-ананың бақылауы', 'Родительский контроль', 'Parental controls'), text: X('Заң бойынша ата-аналар баланың ұялы телефонды пайдалануын және зиянды интернет-ресурстарға кіруін бақылауға міндетті («Білім туралы» Заңның 49-бабы).', 'По закону родители обязаны контролировать использование ребёнком телефона и посещение вредных интернет-ресурсов (ст. 49 Закона «Об образовании»).', 'By law parents must oversee their child’s phone use and access to harmful websites (Law “On Education”, Art. 49).') },
    ], { cols: 3 });

    // ---------------------------------------------------------------- what to do if…
    const faq = ui.accordion([
      { q: X('Мені мазақтайды немесе қорқытады. Не істеймін?', 'Меня обижают или запугивают. Что делать?', 'I’m being teased or threatened. What do I do?'), a: ui.prose(L(X('<ul><li>Үндемей жүрме: ата-анаңа, сынып жетекшісіне немесе мектеп психологына айт. Бұл «шағым» емес — өзіңді қорғау.</li><li>Не болғанын, қашан болғанын және кім істегенін жазып ал.</li><li>Ешкімге айта алмасаң — <a href="tel:150">150</a> немесе <a href="tel:111">111</a> нөміріне қоңырау шал, атыңды айтпауыңа болады.</li></ul>', '<ul><li>Не молчи: расскажи родителям, классному руководителю или школьному психологу. Это не «ябедничество», а защита себя.</li><li>Запиши, что случилось, когда и кто был рядом.</li><li>Если некому рассказать — позвони <a href="tel:150">150</a> или <a href="tel:111">111</a>, имя можно не называть.</li></ul>', '<ul><li>Don’t stay silent: tell your parents, class teacher or the school psychologist. That isn’t “telling tales” — it’s protecting yourself.</li><li>Write down what happened, when, and who was there.</li><li>If there’s no one to tell, call <a href="tel:150">150</a> or <a href="tel:111">111</a> — you don’t have to give your name.</li></ul>'))), open: true },
      { q: X('Балам мектепке барғысы келмейді, тұйықталып кетті', 'Ребёнок не хочет идти в школу, замкнулся', 'My child doesn’t want to go to school and has withdrawn'), a: ui.prose(L(X('<p>Жайлап, айыптамай сөйлесіңіз; ұйқы, тәбет, көңіл-күй өзгерістеріне назар аударыңыз. Сынып жетекшісіне және педагог-психологқа хабарласыңыз — қажет болса, баланы қолдаудың жеке бағдарламасы жасалып, ата-анамен келісіледі.</p>', '<p>Поговорите спокойно, без упрёков; обратите внимание на сон, аппетит, настроение. Свяжитесь с классным руководителем и педагогом-психологом — при необходимости составляется индивидуальная программа сопровождения, которая согласовывается с родителями.</p>', '<p>Talk calmly and without blame; watch for changes in sleep, appetite and mood. Contact the class teacher and the school psychologist — if needed, an individual support programme is drawn up and agreed with you.</p>'))) },
      { q: X('Балама интернетте қорқытып жазады (кибербуллинг)', 'Ребёнку угрожают в интернете (кибербуллинг)', 'My child is being threatened online (cyberbullying)'), a: ui.prose(L(X('<p>Хабарламаларды жоймаңыз — скриншот жасаңыз, агрессорды бұғаттап, платформаға шағымданыңыз. Кибербуллинг те буллинг болып саналады: мектепке хабарлаңыз. Қорқыту, бопсалау немесе жеке суреттерді тарату болса — полицияға (<a href="tel:102">102</a>) жүгініңіз.</p>', '<p>Не удаляйте сообщения — сделайте скриншоты, заблокируйте агрессора и пожалуйтесь платформе. Кибербуллинг тоже является травлей: сообщите в школу. При угрозах, вымогательстве или распространении личных фото обратитесь в полицию (<a href="tel:102">102</a>).</p>', '<p>Don’t delete the messages — take screenshots, block the sender and report them to the platform. Cyberbullying counts as bullying: tell the school. For threats, extortion or shared private images, contact the police (<a href="tel:102">102</a>).</p>'))) },
      { q: X('Мен буллингті көрдім. Қалай көмектесуге болады?', 'Я видел(а) травлю. Как помочь?', 'I saw someone being bullied. How can I help?'), a: ui.prose(L(X('<p>Қорлауға қосылма және күлме. Жәбірленушінің қасында бол, оны оңаша қалдырма. Болған жағдайды міндетті түрде мұғалімге немесе психологқа айт.</p>', '<p>Не присоединяйся и не смейся. Будь рядом с тем, кого обижают, не оставляй его одного. Обязательно расскажи учителю или психологу.</p>', '<p>Don’t join in or laugh. Stay with the person being hurt and don’t leave them alone. Always tell a teacher or the psychologist.</p>'))) },
      { q: X('Бала өзіне зиян келтіру туралы айтады', 'Ребёнок говорит о том, чтобы причинить себе вред', 'A child talks about harming themselves'), a: ui.prose(L(X('<p><strong>Мұны әрдайым байыппен қабылдаңыз.</strong> Баланы жалғыз қалдырмаңыз, сабырлы түрде тыңдаңыз. Тікелей қауіп болса — дереу <a href="tel:112">112</a> немесе <a href="tel:103">103</a>. Кеңес пен қолдау үшін — <a href="tel:111">111</a> (тәулік бойы) немесе <a href="tel:150">150</a>. Мектеп психологына хабарлаңыз: мұндай дағдарыстық жағдайларда қолдау қызметі баланы және ата-анасын психологиялық қолдау орталығына (ПҚО) жібереді.</p>', '<p><strong>Всегда относитесь к этому серьёзно.</strong> Не оставляйте ребёнка одного, выслушайте спокойно. При непосредственной угрозе — сразу <a href="tel:112">112</a> или <a href="tel:103">103</a>. За консультацией и поддержкой — <a href="tel:111">111</a> (круглосуточно) или <a href="tel:150">150</a>. Сообщите школьному психологу: в таких кризисных случаях служба сопровождения направляет ребёнка и родителей в центр психологической поддержки (ЦПП).</p>', '<p><strong>Always take it seriously.</strong> Don’t leave the child alone; listen calmly. If there is immediate danger, call <a href="tel:112">112</a> or <a href="tel:103">103</a> at once. For advice and support, call <a href="tel:111">111</a> (24/7) or <a href="tel:150">150</a>. Tell the school psychologist: in crisis cases the support service refers the child and parents to a psychological support centre.</p>'))) },
      { q: X('Балам басқаларды ренжітеді', 'Мой ребёнок обижает других', 'My child is hurting others'), a: ui.prose(L(X('<p>Бұл да көмек қажет екенінің белгісі. Мектеппен ынтымақтасыңыз: Қағидалар бойынша бастамашы балаға да әлеуметтік бейімделу үшін психологиялық қолдау көрсетіледі. Балаға мінез-құлқының салдарын түсіндіріп, эмпатияны бірге дамытыңыз.</p>', '<p>Это тоже сигнал, что нужна помощь. Сотрудничайте со школой: по Правилам инициатору травли также оказывается психологическая поддержка для социальной адаптации. Объясните ребёнку последствия его поведения и развивайте эмпатию вместе.</p>', '<p>This is also a sign that help is needed. Work with the school: under the Rules the initiator also receives psychological support for social adaptation. Explain the consequences of their behaviour and build empathy together.</p>'))) },
    ], { exclusive: false });

    // ---------------------------------------------------------------- offence prevention (Law No. 245-VIII, Art. 23)
    const LAW245_NAME = X('«Құқық бұзушылық профилактикасы туралы» ҚР Заңы (№ 245-VIII, 2025)', 'Закон РК «О профилактике правонарушений» от 30 декабря 2025 года № 245-VIII', 'Law “On Prevention of Offences” of 30 December 2025 No. 245-VIII');
    const preventionIntro = ui.prose(L(X(
      `<p>Кәмелетке толмағандар арасындағы құқық бұзушылықтың алдын алу бойынша мектептің міндеттері ${ui.extLink(LAW245, '«Құқық бұзушылық профилактикасы туралы» ҚР Заңының (№ 245-VIII, 2025)')} 23-бабында белгіленген. Бұл заң күшін жойған 2004 жылғы 9 шілдедегі «Кәмелетке толмағандар арасындағы құқық бұзушылықтардың, қадағалаусыз және панасыз қалудың профилактикасы туралы» Заңның орнына қабылданды. Төменде — мектептің негізгі міндеттері мен оларды кім орындайтыны.</p>`,
      `<p>Обязанности школы по профилактике правонарушений среди несовершеннолетних установлены статьёй 23 ${ui.extLink(LAW245, 'Закона РК «О профилактике правонарушений» от 30 декабря 2025 года № 245-VIII')}. Этот закон заменил прежний Закон от 9 июля 2004 года «О профилактике правонарушений среди несовершеннолетних…». Ниже — основные обязанности школы и кто их выполняет.</p>`,
      `<p>A school’s duties in preventing offences by and against minors are set out in Article 23 of the ${ui.extLink(LAW245, LAW245_NAME.en)}. It replaced the earlier Law of 9 July 2004 on preventing offences among minors. Below are the school’s main duties and who carries them out.</p>`,
    )));
    const prevention = ui.cards([
      { icon: 'users', title: X('Профилактика кеңесі', 'Совет профилактики', 'Prevention council'), text: X('Мектеп кәмелетке толмағандар арасындағы құқық бұзушылықты анықтау және алдын алу бойынша профилактика кеңесін құрады (23-бап, 14).', 'Школа создаёт совет профилактики по выявлению и предупреждению правонарушений среди несовершеннолетних (ст. 23, пп. 14).', 'The school sets up a prevention council to identify and prevent offences among minors (Art. 23(14)).') },
      { icon: 'shield', title: X('Полицияға дереу хабарлау', 'Немедленное сообщение в полицию', 'Telling the police at once'), text: X('Балалар жасаған немесе оларға қатысты құқық бұзушылық туралы мектеп құқық қорғау органдарына дереу хабарлайды (23-бап, 1).', 'О правонарушениях, совершённых несовершеннолетними или в отношении них, школа незамедлительно сообщает в правоохранительные органы (ст. 23, пп. 1).', 'The school reports offences committed by or against minors to law enforcement immediately (Art. 23(1)).') },
      { icon: 'heart', title: X('Баса назар мен сүйемелдеу', 'Повышенное внимание и сопровождение', 'Extra attention and support'), text: X('Баса назар аударуды талап ететін оқушыларды педагогикалық сүйемелдеу, психологиялық қолдау орталықтарымен бірлесе жұмыс (23-бап, 3, 7).', 'Педагогическое сопровождение обучающихся, требующих повышенного внимания, взаимодействие с центрами психологической поддержки (ст. 23, пп. 3, 7).', 'Pedagogical support for pupils who need extra attention, working with psychological support centres (Art. 23(3), (7)).') },
      { icon: 'calendar', title: X('Сабаққа қатысу есебі', 'Учёт пропусков', 'Attendance watch'), text: X('Дәлелсіз себеппен сабаққа келмейтін балаларды анықтап, есепке алады және олардың ата-аналарымен жұмыс істейді (23-бап, 9).', 'Школа выявляет и учитывает детей, не посещающих занятия без уважительных причин, и работает с ними и их родителями (ст. 23, пп. 9).', 'The school identifies and records children who miss school without good reason and works with them and their parents (Art. 23(9)).') },
      { icon: 'scale', title: X('Құқықтық тәрбие', 'Правовое воспитание', 'Legal awareness'), text: X('Заңға бағынатын мінез-құлықты қалыптастыратын тәрбие бағдарламалары, сынып сағаттары және ата-аналармен жұмыс (23-бап, 4, 10).', 'Воспитательные программы, формирующие законопослушное поведение, классные часы и работа с родителями (ст. 23, пп. 4, 10).', 'Upbringing programmes that build law-abiding behaviour, class hours and work with parents (Art. 23(4), (10)).'), href: href('upbringing') },
      { icon: 'sparkles', title: X('Қолжетімді үйірмелер', 'Доступные кружки', 'Accessible clubs'), text: X('Мектеп балаларға қолжетімді секциялар мен үйірмелердің жұмысын ұйымдастырады (23-бап, 11).', 'Школа организует работу доступных секций и кружков (ст. 23, пп. 11).', 'The school runs accessible clubs and sports sections (Art. 23(11)).'), href: href('clubs') },
    ], { cols: 3 });
    const preventionWho = ui.split({
      ratio: '1:1',
      left: ui.callout({ type: 'info', icon: 'shield', title: X('Полиция инспекторы', 'Инспектор полиции', 'Police inspector'), text: X('Профилактикалық жұмысқа ішкі істер органдары қатысады, оның ішінде кәмелетке толмағандардың істері жөніндегі учаскелік полиция инспекторлары. Мектепке бекітілген инспектордың аты-жөні мен байланысы мектеп растағаннан кейін осында жарияланады.', 'В профилактике участвуют органы внутренних дел, в том числе участковые инспекторы полиции по делам несовершеннолетних. ФИО и контакты инспектора, закреплённого за школой, будут опубликованы здесь после подтверждения школой.', 'The police take part in prevention work, including district police inspectors for juvenile affairs. The name and contacts of the inspector assigned to the school will appear here once the school confirms them.') }),
      right: ui.callout({ type: 'warn', icon: 'doc', title: X('Мектепішілік есеп және КІК', 'Внутришкольный учёт и КДН', 'Internal register and KDN'), text: X('Буллинг бастамашысы мектепішілік есепке қойылады; 6 ай ішінде мінез-құлқы түзелмесе, іс Кәмелетке толмағандардың істері және олардың құқықтарын қорғау жөніндегі комиссияға (КІК) жіберіледі (№ 506 Қағидалардың 12-тармағы).', 'Инициатор травли ставится на внутришкольный учёт; если поведение не изменится в течение 6 месяцев, материалы направляются в комиссию по делам несовершеннолетних и защите их прав (КДН) (п. 12 Правил № 506).', 'A bullying initiator is placed on the school’s internal register; if their behaviour does not improve within 6 months, the case goes to the Commission on Juvenile Affairs (KDN) (Rules No. 506, para 12).') }),
    });
    const preventionPending = ui.pending({
      title: X('Профилактика кеңесі мен жоспары жарияланады', 'Совет профилактики и план будут опубликованы', 'The prevention council and plan will be published'),
      note: X(
        'Профилактика кеңесінің құрамы, мектепке бекітілген полиция инспекторының байланысы және 2026–2027 оқу жылына арналған құқық бұзушылықтың алдын алу жоспары осы жерде жарияланады.',
        'Здесь будут опубликованы состав совета профилактики, контакты инспектора полиции, закреплённого за школой, и план профилактики правонарушений на 2026–2027 учебный год.',
        'The prevention council’s members, the contacts of the police inspector assigned to the school and the 2026–2027 offence prevention plan will be published here.',
      ),
    });
    const docs = ui.docList(['spps-order', 'spps-plan', 'bullying-plan', 'offence-plan', 'prevention-council'].map((id) => ubDoc(docById, id)));

    const sources = ui.linkList([
      { href: R92, icon: 'scale', label: X('Білім беру ұйымдарындағы психологиялық-педагогикалық қолдау қызметінің жұмыс істеу қағидалары (№ 92)', 'Правила деятельности службы психолого-педагогического сопровождения в организациях образования (№ 92)', 'Rules of the psychological and pedagogical support service (No. 92)'), note: 'adilet.zan.kz' },
      { href: R506, icon: 'shield', label: X('Баланы жәбірлеудің (буллингтің) профилактикасы қағидалары (№ 506)', 'Правила профилактики травли (буллинга) ребёнка (№ 506)', 'Rules on preventing bullying of a child (No. 506)'), note: 'adilet.zan.kz' },
      { href: LAW, icon: 'book', label: X('«Білім туралы» ҚР Заңы (49-бап)', 'Закон РК «Об образовании» (ст. 49)', 'Law “On Education” (Art. 49)'), note: 'adilet.zan.kz' },
      { href: LAW245, icon: 'shield', label: X('«Құқық бұзушылық профилактикасы туралы» ҚР Заңы (№ 245-VIII, 23-бап)', 'Закон РК «О профилактике правонарушений» (№ 245-VIII, ст. 23)', 'Law “On Prevention of Offences” (No. 245-VIII, Art. 23)'), note: 'adilet.zan.kz' },
      { href: GOV111, icon: 'phone', label: X('111 байланыс орталығы', 'Контакт-центр 111', 'Contact centre 111'), note: 'gov4c.kz' },
    ]);
    const related = ui.linkList([
      { href: href('parents'), icon: 'handshake', label: X('Ата-аналарға', 'Родителям', 'For parents'), note: X('Ынтымақтастық түрлері және кеңестер', 'Формы сотрудничества и советы', 'Cooperation and advice') },
      { href: href('upbringing'), icon: 'heart', label: X('Тәрбие жұмысы', 'Воспитательная работа', 'Upbringing'), note: X('«Адал азамат» бағдарламасы', 'Программа «Адал азамат»', 'The “Adal Azamat” programme') },
      { href: href('inclusive'), icon: 'accessible', label: X('Инклюзивті білім беру', 'Инклюзивное образование', 'Inclusive education') },
      { href: href('safety'), icon: 'shield', label: X('Қауіпсіздік', 'Безопасность', 'Safety') },
      { href: href('feedback'), icon: 'chat', label: X('Өтініш жолдау', 'Отправить обращение', 'Send a message') },
    ]);

    const toc = ui.toc([
      { id: 'help', label: X('Көмек керек пе?', 'Нужна помощь?', 'Need help?') },
      { id: 'service', label: X('Психологиялық қызмет', 'Психологическая служба', 'Psychological service') },
      { id: 'areas', label: X('Қызметтің бес бағыты', 'Пять направлений работы', 'Five areas of work') },
      { id: 'bullying', label: X('Буллингке — жоқ', 'Нет буллингу', 'Stop bullying') },
      { id: 'procedure', label: X('Буллинг туралы хабар түскенде', 'Если поступило сообщение о травле', 'When bullying is reported') },
      { id: 'cyber', label: X('Киберқауіпсіздік', 'Кибербезопасность', 'Cyber-safety') },
      { id: 'what-if', label: X('Мына жағдайда не істеу керек?', 'Что делать, если…', 'What to do if…') },
      { id: 'prevention', label: X('Құқық бұзушылықтың алдын алу', 'Профилактика правонарушений', 'Offence prevention') },
      { id: 'documents', label: X('Құжаттар', 'Документы', 'Documents') },
    ]);

    return [
      ui.section({ id: 'help', tone: 'arts', eyebrow: X('Көмек керек пе?', 'Нужна помощь?', 'Need help?'), title: X('Сенім телефондары', 'Телефоны доверия', 'Helplines'), lead: X('Қиын жағдайда жалғыз қалмаңыз — қоңырау шалыңыз. Нөмірді басып, бірден қоңырау шалуға болады.', 'В трудной ситуации не оставайтесь одни — позвоните. Нажмите на номер, чтобы позвонить.', 'Don’t face a hard time alone — call. Tap a number to dial.'), body: lines }),
      ui.split({ ratio: '1:2', left: toc, right: ui.section({ id: 'service', eyebrow: X('ППҚҚ', 'СППС', 'Support service'), title: X('Психологиялық-педагогикалық қолдау', 'Психолого-педагогическое сопровождение', 'Psychological and pedagogical support'), body: serviceText }) }),
      ui.section({ id: 'areas', eyebrow: X('№ 92 Қағидалардың 8-тармағы', 'п. 8 Правил № 92', 'Rules No. 92, para 8'), title: X('Қызметтің бес бағыты', 'Пять направлений работы', 'Five areas of work'), body: directions + principles + psychologist }),
      ui.section({ id: 'bullying', tone: 'card', eyebrow: X('Буллингке — жоқ', 'Нет буллингу', 'Stop bullying'), title: X('Буллингтің алдын алу', 'Профилактика буллинга', 'Preventing bullying'), body: definition + zero }),
      ui.section({ id: 'procedure', eyebrow: X('Қадамдар мен мерзімдер', 'Шаги и сроки', 'Steps and deadlines'), title: X('Буллинг туралы хабар түскенде не болады', 'Что происходит, когда поступает сообщение о травле', 'What happens when bullying is reported'), lead: X('Барлық мерзім № 506 Қағидаларда белгіленген. Мектеп өзі не істейтіні (А) және білім басқармасының шешімінен кейін не болатыны (Б).', 'Все сроки установлены Правилами № 506. Что делает сама школа (А) и что происходит после решения управления образования (Б).', 'Every deadline is set by Rules No. 506: what the school does itself (A), and what follows the education department’s decision (B).'), body: procedure + teacherNote }),
      ui.section({ id: 'cyber', eyebrow: X('Цифрлық орта', 'Цифровая среда', 'Digital world'), title: X('Киберқауіпсіздік', 'Кибербезопасность', 'Cyber-safety'), lead: X('Балалар мен ата-аналарға арналған қарапайым ережелер.', 'Простые правила для детей и родителей.', 'Simple rules for children and parents.'), body: cyber }),
      ui.section({ id: 'what-if', eyebrow: X('Жедел жауаптар', 'Быстрые ответы', 'Quick answers'), title: X('Мына жағдайда не істеу керек?', 'Что делать, если…', 'What to do if…'), body: faq }),
      ui.section({ id: 'prevention', tone: 'card', eyebrow: X('Профилактика', 'Профилактика', 'Prevention'), title: X('Құқық бұзушылықтың алдын алу', 'Профилактика правонарушений', 'Offence prevention'), body: preventionIntro + prevention + preventionWho + preventionPending }),
      ui.section({ id: 'documents', eyebrow: X('Құжаттар', 'Документы', 'Documents'), title: X('Қызмет пен профилактика құжаттары', 'Документы службы и профилактики', 'Service and prevention documents'), body: docs }),
      ui.section({ eyebrow: X('Ресми дереккөздер', 'Официальные источники', 'Official sources'), title: X('Нормативтік негіз', 'Нормативная база', 'Legal basis'), body: sources }),
      ui.section({ title: X('Осы бөлімде', 'В этом разделе', 'In this section'), body: related }),
    ].join('\n');
  },
};
